AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  S3BucketName:
    Type: String
    Description: The name of the S3 bucket

  JwtSignKeyLocation:
    Type: String
    Description: The location of the JWT sign key (privateKey.pem) file

  AdminEmail:
    Type: String
    Description: The e-mail of the admin user

  AdminPassword:
    Type: String
    Description: The password of the admin user

  DbPort:
    Type: String
    Description: The port of the RDS database

  DbName:
    Type: String
    Description: The name of the RDS database

  DbUser:
    Type: String
    Description: The user of the RDS database

  DbPassword:
    Type: String
    Description: The password of the RDS database
    NoEcho: true

  TmdbApiKey:
    Type: String
    Description: The The Movie Database API key

  OpenAiApiKey:
    Type: String
    Description: The Open AI API key

Resources:

  MyCinemaS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketName

  MyCinemaRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: mycinema-db
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      DBName: !Ref DbName
      PubliclyAccessible: true
      AllocatedStorage: 20

  MyCinemaElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    DeletionPolicy: Delete
    Properties:
      ApplicationName: MyCinema
      Description: "Application for MyCinema"

  MyCinemaBackendEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: MyCinemaRDSInstance
    DeletionPolicy: Delete
    Properties:
      EnvironmentName: MyCinemaBackend
      ApplicationName: !Ref MyCinemaElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2023 v4.3.2 running Corretto 21"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: vockey
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: LabInstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: JWT_SIGN_KEY_LOCATION
          Value: !Ref JwtSignKeyLocation
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ADMIN_EMAIL
          Value: !Ref AdminEmail
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ADMIN_PASSWORD
          Value: !Ref AdminPassword
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_HOST
          Value: !GetAtt MyCinemaRDSInstance.Endpoint.Address
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_PORT
          Value: !Ref DbPort
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_NAME
          Value: !Ref DbName
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_USER
          Value: !Ref DbUser
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_PASSWORD
          Value: !Ref DbPassword
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: TMDB_API_KEY
          Value: !Ref TmdbApiKey
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: OPENAI_API_KEY
          Value: !Ref OpenAiApiKey

  MyCinemaFrontendEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: MyCinemaBackendEnvironment
    DeletionPolicy: Delete
    Properties:
      EnvironmentName: MyCinemaFrontend
      ApplicationName: !Ref MyCinemaElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2023 v6.2.2 running Node.js 20"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: vockey
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: LabInstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: VUE_APP_API_URL
          Value: !GetAtt MyCinemaBackendEnvironment.EndpointURL

Outputs:

  S3Bucket:
    Description: The name of the S3 bucket
    Value: !Ref MyCinemaS3Bucket

  RDSInstanceEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MyCinemaRDSInstance.Endpoint.Address

  BackendEnvironmentURL:
    Description: The URL of the MyCinemaBackend environment
    Value: !GetAtt MyCinemaBackendEnvironment.EndpointURL

  FrontendEnvironmentURL:
    Description: The URL of the MyCinemaFrontend environment
    Value: !GetAtt MyCinemaFrontendEnvironment.EndpointURL