AWSTemplateFormatVersion: '2010-09-09'

Resources:

  MyCinemaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
    DeletionPolicy: Delete

  MyCinemaRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: mycinema-db
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      DBName: !Ref DbName
      PubliclyAccessible: false
      AllocatedStorage: 20
    DeletionPolicy: Retain

  MyCinemaECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref ECRRepositoryName

Parameters:

  S3BucketName:
    Type: String
    Description: The name of the S3 bucket

  ECRRepositoryName:
    Type: String
    Description: The name of the ECR repository

  DbUser:
    Type: String
    Description: The user of the RDS database

  DbPassword:
    Type: String
    Description: The password of the RDS database
    NoEcho: true

  DbName:
    Type: String
    Description: The name of the RDS database

Outputs:

  S3Bucket:
    Description: The name of the S3 bucket
    Value: !Ref MyCinemaS3Bucket

  RDSInstanceEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MyCinemaRDSInstance.Endpoint.Address

  ECRRepositoryUri:
    Description: The URI of the ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}"