AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCinemaS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
    DeletionPolicy: Delete

  MyCinemaRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: mycinema-db
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      DBName: !Ref DBName
      PubliclyAccessible: false
    DeletionPolicy: Retain

Parameters:
  DBMasterUsername:
    Type: String
    Description: The master username for the RDS database

  DBMasterUserPassword:
    Type: String
    Description: The master password for the RDS database
    NoEcho: true

  DBName:
    Type: String
    Description: The name of the RDS database

  S3BucketName:
    Type: String
    Description: The name of the S3 bucket

Outputs:
  S3Bucket:
    Description: The name of the S3 bucket
    Value: !Ref MyCinemaS3Bucket

  RDSInstanceEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MyCinemaRDSInstance.Endpoint.Address