AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  BackendBucketName:
    Type: String
    Description: The name of the backend's S3 bucket

  FrontendBucketName:
    Type: String
    Description: The name of the frontend's S3 bucket

  JwtSignKeyLocation:
    Type: String
    Description: The location of the JWT sign key (privateKey.pem) file

  AdminEmail:
    Type: String
    Description: The e-mail of the admin user

  AdminPassword:
    Type: String
    Description: The password of the admin user

  DbHost:
    Type: String
    Description: The host of the database

  DbPort:
    Type: String
    Description: The port of the database

  DbName:
    Type: String
    Description: The name of the database

  DbUser:
    Type: String
    Description: The user of the database

  DbPassword:
    Type: String
    Description: The password of the database
    NoEcho: true

  TmdbApiKey:
    Type: String
    Description: The The Movie Database API key

  OpenAiApiKey:
    Type: String
    Description: The Open AI API key

Resources:

  MyCinemaBackendBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BackendBucketName

  MyCinemaFrontendBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref FrontendBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  MyCinemaElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    DeletionPolicy: Delete
    Properties:
      ApplicationName: MyCinema
      Description: "Application for MyCinema"

  MyCinemaBackendEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DeletionPolicy: Delete
    Properties:
      EnvironmentName: MyCinemaBackend
      ApplicationName: !Ref MyCinemaElasticBeanstalkApplication
      SolutionStackName: "64bit Amazon Linux 2023 v4.3.2 running Corretto 21"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: vockey
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: LabInstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: JWT_SIGN_KEY_LOCATION
          Value: !Ref JwtSignKeyLocation
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ADMIN_EMAIL
          Value: !Ref AdminEmail
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ADMIN_PASSWORD
          Value: !Ref AdminPassword
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_HOST
          Value: !Ref DbHost
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_PORT
          Value: !Ref DbPort
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_NAME
          Value: !Ref DbName
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_USER
          Value: !Ref DbUser
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_PASSWORD
          Value: !Ref DbPassword
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: TMDB_API_KEY
          Value: !Ref TmdbApiKey
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: OPENAI_API_KEY
          Value: !Ref OpenAiApiKey

Outputs:

  BackendURL:
    Description: The URL of the MyCinema's backend
    Value: !Sub 'http://${MyCinemaBackendEnvironment.EndpointURL}'
    Export:
      Name: BackendURL

  FrontendURL:
    Description: The URL of the MyCinema's frontend
    Value: !Sub 'http://${MyCinemaFrontendBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Export:
      Name: FrontendURL